### ISSUE TITLE
in bbWW we use only one part of HH sample for training

### ISSUE THREAD

**Issue by acarvalh** [HEP-KBFI/hh-bbww#15]
We do not need two trainings.

By now, the half of the HH non-res LO events (== events that need reweighing) not used in application is the odd one.
In the BDT mode it loads all.

That is followed in [this commit](https://github.com/HEP-KBFI/hh-bbww/commit/17b5cdc88dca68f4c64189b7e27e513fd94f8d01) and [this commit](https://github.com/HEP-KBFI/hh-bbww/commit/e99bfed91afd2f848d8f98f880c2baa8227d6e5f)

One needs to pay attention

1) add resonant to the logic in default mode
2) In training code explicitly throw away the part to be used on application

ps.: as no training is done in HH non-res NLO that does not need to be added to this logic

**Comment by veelken** [comment]
Hi Xandra,

sorry, what is the motivation for introducing this special case ?
Why should we not use the standard odd-even method for all BDTs and all LBNs regardless of if we are processing signal MC, background MC, or data ?

Cheers,


Christian

**Comment by acarvalh** [comment]
Hi

There is nothing new there.
That is what we do for tHq sample in ttH analysis, for instance (we used 1/3 to application and 2/3 for training). Also there [I wrote first really like this there, then Karl encapsulated in a fancy way.](https://github.com/HEP-KBFI/tth-htt/commit/eff9c998f5f84f5b7462226911e67eadfe65baa2). I just did not make his fancy way.

The motivation of doing differently from HH multilepton is that in bbWW we do have sample statistics to make only one MVA file. That is what I argued in this talk [slide 5](https://indico.cern.ch/event/922780/contributions/3943328/attachments/2073141/3480837/HH_bbWW_training_strategies.pdf) and there was no opposition to it, so I went ahead.

However, as in bbWW there are other groups doing MVA's other than in TLL fw I will do later today a survey in Skype on what the other groups are doing since at least you did not get that comment. 
The idea is we all be uniform and avoid confusion of each BDT case doing it differently (in case they intend to do differently).

cheers

**Comment by acarvalh** [comment]
By not I will convert best to the 2-fold method for the sake of baseline.

We keep in mind thought that for DNNs the plan seem to be using [cross validation](https://en.wikipedia.org/wiki/Cross-validation_(statistics)) == in poor wording, having one MVA file to all events and this file will do the magic
