### ISSUE TITLE
Skim samples for bb1l analysis

### ISSUE THREAD

**Issue by ktht** [HEP-KBFI/hh-bbww#19]
Require at least one fakeable lepton in the skimming, no limits on the multiplicity of hadronic taus. Maybe this has the potential to shorten the time needed in producing the datacards.

**Comment by acarvalh** [comment]
For the record here in timing;

With 1 file per run, no shape syst and booking 81 data/MC plots on to of 24 MVAs histograms in evt that is taking ~ 6-8h

**Comment by ktht** [comment]
So I checked the runtime details of your jobs and found that each job analyzed 1 input file and ran 10 minutes on average. Since skimming wasn't really that effective, I think the best way to go is to keep using unskimmed samples with 20 input files per analysis job. This will generate about 9k analysis jobs with full systematics, each running 2-3h, or ca 30k CPU hours per run. In other words: performance is not an issue here as I initially thought; nothing to be done here.
