### ISSUE TITLE
Run HME with MEM in bb2l channel

### ISSUE THREAD

**Issue by ktht** [HEP-KBFI/hh-bbww#2]
Since running HME is quite an expensive task, it's somewhat prohibitive to run it in the analysis job. Creating dedicated workflow for HME analogous to MEM is out of the question as well because it has a lot of overhead in terms of human time -- setting up the workflow takes substantial amount of time, plus the bookkeeping becomes more complex, because we would have to deal with multiple sets of Ntuples: without HME and MEM, with HME and without MEM and with both HME and MEM.

Compared to MEM, however, HME is relatively fast. Considering that the we need to compute MEM and HME in the same channel, it makes sense to move the HME computation to the sample place where MEM is computed, so that both are computed in one go. The only downside to this are the shape uncertainties: if the JES or JER are varied, it may alter the estimated HH mass computed by HME. There are multiple options to handle it:
1. simply ignore the effect of JetMET shape systematics on HME results and compute it from central values only;
2. compute HME with central values, but introduce additional shape systematics pertaining to HME in the analysis job that varies the di-Higgs mass of HME by X% which is determined by analyzing the effect of shape systematics on HME in a bbWW sample;
3. compute HME mass for all JetMET shape systematics in one job. It obviously increases the runtime spent on HME substantially.

The MEM is implemented with the 3rd option in mind, but in practice we effectively use the 1st option and run MEM on the central values while ignoring the effects of shape systematics, in order to save some computing time. I think it's worth to:
- benchmark HME: estimate how much the runtime increases in MEM+HME job when running with central values and with full systematics for HME (while keeping MEM at central values only);
- compare HME results for different shape systematics. This way we can gain some insight how much the HME mass is affected by shape uncertainties, plus it also tests the stability of the HME algorithm and its implementation;
- if the runtime doesn't substantially increase, then stick to the 3rd option; otherwise, implement either 1st or 2nd option.

The task itself can be broken down into following steps:
- move everything HME-related from `analyze_hh_bb2l.cc` to `addMEM_hh_bb2l.cc`;
- analogously to `MEMOutputReader_hh_bb2l` and `MEMOutputWriter_hh_bb2l`, create classes that read and write HME masses from/to a TTree. The HME branch names should at the very least encode the systematics name (as is the case with MEM). The writer class should be used in HME+MEM jobs and reader class in bb2l analysis jobs;
- provide a boolean or two to tell MEM+HME job that the given list of systematics applies to HME, MEM, or both. This has the benefit that if the 3rd option becomes viable, we necessarily don't want to compute MEM score for all shape systematics.

The testing & validation should be done using sync Ntuple:
- produce sync Ntuple for all JetMET systematics in bb2l channel;
- implement the solution as described in the previous paragraph;
- produce a new sync Ntuple and compare the results;
- estimate the effect of shape systematics on HME and optimize for speed if necessary.

**Comment by ktht** [comment]
What's the status of this issue?

**Comment by acarvalh** [comment]
While I am finishing to implement the MEM by benchmarck I see it HME there, I am not sure who implemented, but seems to be working (booking and reading)

**Comment by saswatinandan** [comment]
Hi Karl,

 As far as I remember, in one of the weekly meetings you told that you would send me the instructions, but I didn't receive anything later. Sorry if I miss anything.

Thanks,
Saswati
________________________________________

**Comment by ktht** [comment]
@saswatinandan confirmed that the issue is resolved. The solution also involved a fix in our fork of the HME repository, so everyone please make sure to update it as well.

**Comment by veelken** [comment]
Hi Karl, 

I am a bit confused about your comment concerning our fork of the HME repository.
The latest version of the HME code is in Tao's repository ( https://github.com/tahuang1991/HeavyMassEstimator , according to our installation instructions https://twiki.cern.ch/twiki/bin/viewauth/CMS/TTHtautauFor13TeV-Tallinn#Setup_for_CMSSW_version_10_2_x ; I believe I have been the last person who updated the installation instructions for the HME algorithm on this twiki).

**Comment by ktht** [comment]
Sorry, it's me who told Saswati to push additional changes to our fork. I didn't pay attention to the instructions on Twiki (and frankly I dislike the way we have to access the installation instruction). I saw that you've also implemented the same changes in our fork as well, so it shouldn't matter which one we use, right?

I think we should either:
- propagate Saswati's changes to the usptream via PR, delete our fork and always stick to the upstream; or
- use the fork, forget about the upstream repository.

The upside of using a fork is that everyone in our group can get write access quickly which cannot be said about the upstream repository. I have no strong opinions, however, if we want to stick to the upstream, I strongly suggest that we delete our fork to avoid any further confusion.
