### ISSUE TITLE
Missing systematics

### ISSUE THREAD

**Issue by ktht** [HEP-KBFI/hh-bbww#39]
After yesterday's discussion it seems that we're still missing some systematic uncertainties that other groups have implemented:
1. JMS, JMR -- we already have them, just need to re-enable them again;
2. Uncertainty associated with correcting LO W+jets spectrum to NLO using LHE info -- more details at AN2019/229v6, section 4.4.3;
3. ~PS uncertainties on other backgrounds besides ttbar -- will have to check if it's possible to add them, and if not then need to understand why. Correlation still up for debate (imo);~ (see my next post)
4. Uncertainty associated with b-tagging SFs on AK8 subjets.

The first two points are easy enough; the third requires some investigation. The fourth item is the most challenging, because our Ntuples simply lack the information needed to compute these SFs. Will need to discuss what our options are, because I don't think we can just ignore them since they rank relatively high in terms of impact.

**Comment by ktht** [comment]
Interim update: JMS and JMR are now enabled. Implemented LO-to-NLO corrections for W+jets samples. Its uncertainty is named as `Vpt_nlo`, so no need to rename it. One thing that concerns me a bit is that the W+jets background will increase by roughly 50% after this change. Either this background must be so small that it didn't show up in data/MC comparison, or there's going to be a problem.

 As for the PS weights, after closer inspection it looks like
- in 2016, there are no resonant SL or DL samples with PS weights;
- in 2017, only half of resonant SL samples have PS weights while none of the resonant DL samples have them;
- in 2018, all resonant samples have PS weights.

Thus, I see little point in implementing it for the signal samples. I'll work on subjet b-tagging next week.

**Comment by ktht** [comment]
I cannot find the place in the code where we require b-tagged subjets to have pT > 30 GeV. It has some (arguably minor) implications in determining the event-level weight from subjet b-tagging SFs.

**Comment by saswatinandan** [comment]
I guess it is implemented here ?

https://github.com/HEP-KBFI/hh-bbww/blob/master/src/RecoJetCollectionSelectorAK8_hh_bbWW_Hbb.cc#L226
________________________________

**Comment by ktht** [comment]
Thanks, that settles it.

I discussed the details of computing the b-tagging SFs for AK8 subjets with Louvain. The [recommendation](https://hypernews.cern.ch/HyperNews/CMS/get/btag/1812/1/1/1.html) is to use method 1a in [BTV Twiki](https://twiki.cern.ch/twiki/bin/view/CMS/BTagSFMethods). This implies that we compute the subjet b-tagging efficiencies from MC in bins of pT, |eta| and hadron flavor of the AK8 subjet. I'll create another workflow in [`tthProjection.py`](tthProjection.py) that determines these efficiencies.

**Comment by ktht** [comment]
Well.. I made a mistake in my assessment that we have access to hadron flavors of AK4 gen jets in our post-processed Ntuples. I had this impression because we have dedicated [`GenJetReader`](https://github.com/HEP-KBFI/tth-htt/blob/master/interface/GenJetReader.h) that could've been easily modified to read the hadron flavor branch -- but I never actually looked what's inside the post-processed Ntuples. Turns out that we used [`GenParticleWriter`](https://github.com/HEP-KBFI/tth-htt/blob/242ea8d8a247288eab44a6690cce5deddff92eca/bin/produceNtuple.cc#L456) to transcribe the `GenJet` collection, so hadron flavor information is completely lost in post-production.

This has two implications:
1. we have to use generator-level partons that are available in our post-processed Ntuples (`GenQuarkFromTop`, `GenBQuarkFromTop`, `GenWZQuark` and `GenHiggsDaughters`) and dR-match them to subjets;
2. we can derive the SF only for the backgrounds that contain at least one top quark, hadronically decaying vector boson or Higgs. We cannot derive these SF for eg W+jets or DY. To keep things simpler, we'll apply the SF only to ttbar and to HH signal.

If these SFs cause any problems in dedicated SL fits or SL+DL combination, we always have the option to post-process the Ntuples again such that we could use the hadron flavor of matched AK4 gen jets as proxy to AK8 subjet flavor. I would delay these efforts unless really necessary.

**Comment by ktht** [comment]
All corrections and uncertainties are implemented. However, there seems to be a problem with the LHE Vpt reweighting that needs to be investigated on a longer time scale. For now I've disabled the corrections (and associated systematics). I'll keep the thread open until this last item is resolved.

@saswatinandan Please update: this repository, ttH repository and `$CMSSW_BASE/src/PhysicsTools/NanoAODTools` repository before submitting any jobs.

**Comment by ktht** [comment]
Ok so we're not going to apply these corrections to LO samples at all but try out NLO W+jets samples instead. I'll refresh my memory on how to do it all over again and start with the Ntuple production asap.

**Comment by veelken** [comment]
Thank you very much, Karl!

**Comment by ktht** [comment]
@saswatinandan samples are ready. You now have to specify in the command line which samples you want to use:
- `-W lo` if you want to use LO samples;
- `-W nlo` if you want to use NLO samples.
