### ISSUE TITLE
uniformize H proc naming

### ISSUE THREAD

**Issue by acarvalh** [HEP-KBFI/hh-bbww#6]
Uniformize H proc (TTH, TH, VH) namings/decays wrt to ttH analysis to apply correctly systematics.
Adapt the HH names to be easier deal with BR uncertainties in the combineHavester step.

**Comment by acarvalh** [comment]
Adding comment

following [this](https://gitlab.cern.ch/cms-hh-bbww/cms-hh-to-bbww/-/blob/master/Legacy/datacards_and_systematics.md#11-single-higgs-processes) naming convention. 

For single H processes, follow as it is done on the ttH multi lepton codes.

**Comment by acarvalh** [comment]
The renaming of the HH is done instead [here](https://github.com/HEP-KBFI/CombineHarvester/blob/ebae849f7f7a530996cf9515ee8889314c2c12d2/ttH_htt/test/rename_procs.py), in KBFI CombineHarvester

==> that may evolve with some time for the signal extraction methods, so it is easier/faster to do it a posteriori than run again all jobs just because of a fast renaming. 

For single H processes, however, you still need to follow as it is done on the ttH multi lepton codes for separating BRs and use the above-mentioned naming convention.
So, this issue is kept open.

**Comment by acarvalh** [comment]
Check why ggH and qqH are not on the final results, if maybe they get by mistake merged with "Other" or really just do not pass selections

**Comment by ktht** [comment]
These processes have their own category (`ggH`, `qqH`). The reason why they don't end up in the final datacards is because they're not listed here:
https://github.com/HEP-KBFI/hh-bbww/blob/66a4fe8f5461f2ac1a2ba1c9c86c4458fe86111e/python/configs/analyzeConfig_hh_bb1l.py#L118
https://github.com/HEP-KBFI/hh-bbww/blob/66a4fe8f5461f2ac1a2ba1c9c86c4458fe86111e/python/configs/analyzeConfig_hh_bb2l.py#L126

**Comment by ktht** [comment]
This issue can be closed because the way we handle the histograms that are needed in datacard production has been refactored. With the new approach the splitting of single Higgs and di-Higgs processes by their Higgs decay modes are automatically taken care of.
