### ISSUE TITLE
XS normalizations HH signal (NLO and VBF)

### ISSUE THREAD

**Issue by acarvalh** [HEP-KBFI/hh-bbww#7]
In the non-resonant powheg NLO HH and the non resonant VBF ones ones (anomalous couplings included) we need to have it normalized to the sample cross section as from HXSWG for interpretation (not necessarily the MCM one). 
I would find and table of them, but then I find the safest solution is to re-do the samples dictionary to update the normalizations consistently (if that is automatic).

**Comment by acarvalh** [comment]
For reference the cross sections are

VBF_HH_CV_1_C2V_1_C3_1      0.001668                                 
VBF_HH_CV_1_C2V_1_C3_0      0.004454                                              
VBF_HH_CV_1_C2V_1_C3_2      0.001375                                                 
VBF_HH_CV_1_C2V_2_C3_1      0.01374                                                      
VBF_HH_CV_0_5_C2V_1_C3_1    0.01046                                                     
VBF_HH_CV_1_5_C2V_1_C3_1    0.0638                                                       
VBF_HH_CV_1_C2V_0_C3_1      0.02617   

Plus you need to scale all samples to the k_NNLO = xs_SM(N3LO) / xs_SM(LO) = 1.726/1.668 = 1.034


________________________________

ggHH : 
 
  ggHH_kl_1_kt_1  :  0.02675
  ggHH_kl_0_kt_1 : 0.06007
  ggHH_kl_5_kt_1 : 0.07903
  ggHH_kl_2p45_kt_1 : 0.01133

plus you need to scale them with k = 1.115  which is sigma_NNLO+FTapprox / sigma_NLO for SM = 31.05/27.84
================================================

**Comment by ktht** [comment]
I agree that it's easier to do it one place and propagate the figures to the python dictionaries automatically. I'll update them in a few days.

**Comment by ktht** [comment]
Updated the cross sections as you described. Please close the issue if you think it's resolved now.
