### ISSUE TITLE
Update top pT reweighting method in all HH analyses

### ISSUE THREAD

**Issue by ktht** [HEP-KBFI/hh-bbww#8]
Plan to switch to "fit2" described on slide 12 of [this](https://indico.cern.ch/event/904971/contributions/3857701/attachments/2036949/3410728/TopPt_20.05.12.pdf) presentation because it's more accurate at higher energy scales (that we may reach in resonant searches).

**Comment by ktht** [comment]
Feature implemented; requires an update in ttH, HH multilepton and HH bbWW repositories.

**Comment by ktht** [comment]
ttbar sync Ntuples also need an update -> I'm updating those.

**Comment by ktht** [comment]
The ttbar sync Ntuples are updated, but because we've agreed to use quadratic fit of the top pT reweighting in the synchronization exercise, I've changed it back over here: https://github.com/HEP-KBFI/hh-multilepton/blob/d3dac239a55c39837da80690a6e19d2de649b99a/python/configs/analyzeConfig_hh.py#L39

**Comment by veelken** [comment]
Hi Karl,

I suggest we switch to the new (high pT) top pT reweighting for the sync as well. In fact, Florian has already switched. Ok ?

Cheers,


Christian
